/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telaMedico.telaCadastroMedico;

import contoller.MedicoController;
import java.util.Date;
import javax.swing.JOptionPane;
import view.Mensagem;

/**
 *
 * @author Marta
 */
public class TelaCadastroMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroMedico
     */
    
    private MedicoController controlador;
    
    public TelaCadastroMedico() {
        initComponents();
        this.controlador = new MedicoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTituloMedico = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        txtCRM = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputEspecialidade = new javax.swing.JTextField();
        calendarDataNascimento = new com.toedter.calendar.JDateChooser();
        inputCRM = new javax.swing.JTextField();
        comboBoxPeriodo = new javax.swing.JComboBox<>();
        txtPeriodo1 = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JTextField();
        txtPeriodo2 = new javax.swing.JLabel();
        comboBoxConsultorio = new javax.swing.JComboBox<>();
        inputEndereco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/topo.png"))); // NOI18N
        jLabel1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/topo.png"))); // NOI18N
        jLabel2.setToolTipText("");

        txtTituloMedico.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        txtTituloMedico.setText("Cadastro Médico");

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.setText("Nome");

        txtDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDataNascimento.setText("Data de Nascimento");

        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEndereco.setText("Endereço");

        txtTelefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefone.setText("Telefone");

        txtCRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCRM.setText("CRM");

        txtPeriodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPeriodo.setText("Período");

        comboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vespertino", "Matutino" }));
        comboBoxPeriodo.setSelectedIndex(-1);

        txtPeriodo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPeriodo1.setText("Especialidade");

        txtPeriodo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPeriodo2.setText("Consultório");

        comboBoxConsultorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultório 1", "Consultório 2" }));
        comboBoxConsultorio.setSelectedIndex(-1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTituloMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataNascimento)
                            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco)
                            .addComponent(txtTelefone))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(comboBoxConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(inputCRM, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(calendarDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                                        .addGap(0, 319, Short.MAX_VALUE)))
                                .addGap(229, 229, 229))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(63, 63, 63)
                .addComponent(btnCadastrar)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTituloMedico)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataNascimento)
                    .addComponent(calendarDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCRM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeriodo1)
                            .addComponent(inputEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeriodo)
                            .addComponent(comboBoxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriodo2)
                            .addComponent(comboBoxConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco)
                            .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(inputCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCadastrar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            // recebendo e validando dados da interface gráfica
            
            String periodoComboBox = (String) this.comboBoxPeriodo.getSelectedItem();
            String consultorioComboBox = (String) this.comboBoxConsultorio.getSelectedItem();
            
            String nome = "";
            Date dataNascimento = null;
            int crm = 0;
            String especialidade = "";
            String periodo = "";
            String consultorio = "";
            String endereco = "";
            String telefone = "";
            
           
            if (this.inputNome.getText().length() < 2) {
                throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.inputNome.getText();
            }

            if (this.calendarDataNascimento.getDate() == null) {
                throw new Mensagem("Informe uma data de nascimento válida");
            } else {
                dataNascimento = calendarDataNascimento.getDate();
            }
                       
            if (this.inputCRM.getText().length() <= 0) {
                throw new Mensagem("Informe um número de CRM válido");
            } else {
                crm = Integer.parseInt(this.inputCRM.getText());
            }

            if (this.inputEspecialidade.getText().length() < 2) {
                throw new Mensagem("Especialidade deve conter ao menos 2 caracteres.");
            } else {
                especialidade = this.inputEspecialidade.getText();
            }
            
            if (this.comboBoxPeriodo.getSelectedIndex() == -1) {
                throw new Mensagem("Selecione o período correspondente.");
            } else {
                periodo = (String) this.comboBoxPeriodo.getSelectedItem();
            }
            
            if (this.comboBoxConsultorio.getSelectedIndex() == -1) {
                throw new Mensagem("Selecione o consultório correspondente.");
            } else {
                consultorio = (String) this.comboBoxConsultorio.getSelectedItem();
            }
            
            if (this.inputEndereco.getText().length() <= 0) {
                throw new Mensagem("Endereço deve conter ao menos 2 caracteres.");
            } else {
                endereco = this.inputEndereco.getText();
            }
            if (this.inputTelefone.getText().length() <= 0) {
                throw new Mensagem("Telefone deve ser um número e conter 9 dígitos.");
            } else {
                telefone = this.inputTelefone.getText();
            }
           
            periodo = periodo.toUpperCase();
                     
            if (consultorio.equals("Consultório 1")) {
                consultorio = "CONSULTORIO_1";
            }
            else if (consultorio.equals("Consultório 2")) {
                consultorio = "CONSULTORIO_2";
            }


            //envia os dados para o Controlador cadastrar
            if (this.controlador.cadastrar(crm, especialidade, periodo, consultorio, nome, dataNascimento, endereco, telefone)) {
                JOptionPane.showMessageDialog(rootPane, "Médico cadastrado com sucesso!");

                this.inputNome.setText("");
                this.calendarDataNascimento.setDate(null);
                this.inputCRM.setText("");
                this.inputEspecialidade.setText("");
                this.comboBoxPeriodo.setSelectedIndex(-1);
                this.comboBoxConsultorio.setSelectedIndex(-1);
                this.inputEndereco.setText("");
                this.inputTelefone.setText("");
            }

            System.out.println(this.controlador.getMinhaLista().toString());

        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());

        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private com.toedter.calendar.JDateChooser calendarDataNascimento;
    private javax.swing.JComboBox<String> comboBoxConsultorio;
    private javax.swing.JComboBox<String> comboBoxPeriodo;
    private javax.swing.JTextField inputCRM;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputEspecialidade;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtCRM;
    private javax.swing.JLabel txtDataNascimento;
    private javax.swing.JLabel txtEndereco;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPeriodo;
    private javax.swing.JLabel txtPeriodo1;
    private javax.swing.JLabel txtPeriodo2;
    private javax.swing.JLabel txtTelefone;
    private javax.swing.JLabel txtTituloMedico;
    // End of variables declaration//GEN-END:variables
}
